version: '3.6'

services:
  chatbot:
    build: .
    ports:
      - 3001:3000
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEFAULT_MODEL: ${DEFAULT_MODEL}
      NEXT_PUBLIC_NEXTAUTH_ENABLED: ${NEXT_PUBLIC_NEXTAUTH_ENABLED}
      NEXTAUTH_EMAIL_PATTERN: ${NEXTAUTH_EMAIL_PATTERN}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      STORAGE_TYPE: ${STORAGE_TYPE}
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_HOST: ${COUCHDB_HOST}
      COUCHDB_PORT: ${COUCHDB_PORT}
      RDBMS_HOST: ${RDBMS_HOST}
      RDBMS_PORT: ${RDBMS_PORT}
      RDBMS_DB: ${RDBMS_DB}
      RDBMS_USER: ${RDBMS_USER}
      RDBMS_PASS: ${RDBMS_PASS}
      RDBMS_SYNCHRONIZE: ${RDBMS_SYNCHRONIZE}
      RDBMS_SSL_ENABLED: ${RDBMS_SSL_ENABLED}
      RDBMS_SSL_HOST: ${RDBMS_SSL_HOST}
      RDBMS_SSL_CA: ${RDBMS_SSL_CA}
      RDBMS_SSL_CERT: ${RDBMS_SSL_CERT}
      RDBMS_SSL_KEY: ${RDBMS_SSL_KEY}
      RDBMS_COCKROACHDB_TIME_TRAVEL_QUERIES: ${RDBMS_COCKROACHDB_TIME_TRAVEL_QUERIES}
    depends_on:
      - couchdb
    networks:
      - chatbot

  couchdb:
    image: couchdb:3
    ports:
      - 5984:5984
    volumes:
      - ./couchdb.ini:/opt/couchdb/etc/local.d/00-local.ini
    #   - './data:/opt/couchdb/data'
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    networks:
      - chatbot

networks:
  chatbot:
